# SPDX-License-Identifier: GPL-3.0-or-later
"""Read-back of the metal-fill coverage map onto a KiCad viewer layer.

The metal density fill itself lives in the GDS (generated by the interposer PDK
engine during export), so it is invisible in the KiCad canvas. This paints the
coarse, non-authoritative coverage map the worker computed
(``<gds>.fill_coverage.json``) onto a KiCad drawing layer, so the designer gets
a canvas glance at where fill landed and how dense it is.

It is a viewer aid only: nothing downstream reads these shapes, and the export
never depends on them. The shapes are grouped so a later repaint replaces the
previous one instead of accumulating.

pcbnew is imported at module load on purpose: this module only ever runs inside
KiCad (called from the dialog on the UI thread, because pcbnew board edits are
not thread-safe). The host-testable logic lives in the worker
(hyp_to_gds._compute_fill_coverage), not here.
"""

import json

import pcbnew

# Dedicated read-back layer, used when the board defines a user layer with this
# exact name; otherwise we fall back to Dwgs.User (always present). Keeping the
# paint on a dedicated layer lets the designer toggle it independently.
COVERAGE_LAYER_NAME = "FillCoverage"
# Group name so a repaint can find and drop the previous coverage cleanly.
COVERAGE_GROUP_NAME = "fill_coverage"


def _iu(um):
    """Micrometres -> KiCad internal units (nanometres)."""
    return int(round(um * (pcbnew.PCB_IU_PER_MM / 1000.0)))


def _resolve_layer(board):
    """Layer id to paint on: a user layer literally named COVERAGE_LAYER_NAME
    when the board has one, else Dwgs.User. Returns (layer_id, dedicated?)."""
    try:
        for layer_id in board.GetEnabledLayers().Seq():
            if board.GetLayerName(layer_id) == COVERAGE_LAYER_NAME:
                return layer_id, True
    except Exception:
        pass
    return pcbnew.Dwgs_User, False


def clear_fill_coverage(board):
    """Remove a previous coverage paint (its group and the group's shapes).

    Idempotent; returns the number of items removed. Only touches items in the
    COVERAGE_GROUP_NAME group, so a fall-back paint on Dwgs.User never deletes
    the designer's own drawings.
    """
    removed = 0
    try:
        groups = list(board.Groups())
    except Exception:
        return 0
    for group in groups:
        try:
            if group.GetName() != COVERAGE_GROUP_NAME:
                continue
            for item in list(group.GetItems()):
                board.Remove(item)
                removed += 1
            board.Remove(group)
        except Exception:
            continue
    return removed


def paint_fill_coverage(board, coverage_json_path, min_coverage=0.0):
    """Paint the coarse coverage grid onto the read-back layer.

    Reads ``<gds>.fill_coverage.json`` (cells in the GDS frame: micrometres,
    Y up), draws one unfilled rectangle per cell whose coverage exceeds
    ``min_coverage`` on the read-back layer, negating Y back into the KiCad
    frame, and groups them so a later repaint replaces this one.

    Returns the number of cells painted (0 -> nothing drawn, prior paint left
    cleared).
    """
    try:
        with open(coverage_json_path) as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return 0
    cells = (data or {}).get("grid", [])

    clear_fill_coverage(board)
    if not cells:
        return 0

    layer_id, _dedicated = _resolve_layer(board)

    group = pcbnew.PCB_GROUP(board)
    group.SetName(COVERAGE_GROUP_NAME)
    board.Add(group)

    painted = 0
    for cell in cells:
        try:
            if float(cell.get("coverage", 0.0)) <= min_coverage:
                continue
            x = float(cell["x_um"])
            y = float(cell["y_um"])
            w = float(cell["w_um"])
            h = float(cell["h_um"])
        except (KeyError, TypeError, ValueError):
            continue
        shape = pcbnew.PCB_SHAPE(board)
        shape.SetShape(pcbnew.SHAPE_T_RECT)
        shape.SetLayer(layer_id)
        try:
            shape.SetFilled(False)
        except Exception:
            pass
        # GDS Y-up -> KiCad Y-down: negate Y, so a cell [y, y+h] maps to
        # [-(y+h), -y] and stays axis-aligned.
        shape.SetStart(pcbnew.VECTOR2I(_iu(x), _iu(-(y + h))))
        shape.SetEnd(pcbnew.VECTOR2I(_iu(x + w), _iu(-y)))
        board.Add(shape)
        group.AddItem(shape)
        painted += 1

    if painted == 0:
        clear_fill_coverage(board)
    return painted
