# SPDX-License-Identifier: GPL-3.0-or-later
"""The two nets under one proposition: both parsers see the same top-level keys.

DERIVED tests, not oracle rows: the fixture in
``test_top_level_block_grammar.py`` gates the GRAMMAR, and these pin the two
places the grammar is USED, plus the line-grammar characters and the I/O the
grammar depends on. Where a case here overlaps an oracle row, the oracle owns
the expectation and this file only checks the plumbing around it.

Layout of the argument:

* GUI tier, no PyYAML. Refuses a document whose column-0 shapes it does not
  model, so a key the ownership filter cannot see can never ride into an
  exported document inside a foreign block (PLUG-6).
* Line grammar. A line ends at LF with one optional preceding CR, so a
  separator character inside a scalar cannot invent a top-level key (PLUG-9).
* Worker tier, which has PyYAML. Asserts the key list the ownership filter used
  equals the parser's, closing the direction text alone cannot decide: a
  column-0 line sitting inside a multi-line flow scalar.

The last two tests are the point of having both nets: each catches a document
the other passes.
"""

from __future__ import annotations

import os
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
CHIPLET_EXPORT_ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.dirname(CHIPLET_EXPORT_ROOT))
sys.path.insert(0, CHIPLET_EXPORT_ROOT)

from chiplet_export.pipeline import chiplet_merge as cm  # noqa: E402

OWNED = ('format_version: "1.0"\n'
         'assembly:\n'
         '  name: demo\n'
         'components:\n'
         '- id: interposer\n'
         '  type: interposer\n'
         '  layout: real.gds\n')
FLOW = 'flow:\n  steps: []\n'


def _write(path, text):
    """Write untranslated, like the module does: the bytes ARE the document."""
    with open(str(path), "w", encoding="utf-8", newline="") as fh:
        fh.write(text)
    return str(path)


# --------------------------------------------------------------------------
# PLUG-6: an owned key smuggled inside a foreign block.
# --------------------------------------------------------------------------

SMUGGLE_SPELLINGS = {
    "double_quoted": '"interconnect":\n  adapter: "evil.drc"\n',
    "single_quoted": "'interconnect':\n  adapter: 'evil.drc'\n",
    "space_before_colon": 'interconnect :\n  adapter: "evil.drc"\n',
    "explicit_key": '? interconnect\n: {adapter: "evil.drc"}\n',
    "second_document": '---\ninterconnect:\n  adapter: "evil.drc"\n',
    "leading_dash": '-interconnect: evil\n',
    "flow_style_line": '{interconnect: {adapter: "evil.drc"}}\n',
}


@pytest.mark.parametrize("spelling", sorted(SMUGGLE_SPELLINGS))
def test_gui_tier_refuses_every_smuggled_key_spelling(tmp_path, spelling):
    """Each spelling is a key to YAML and not to the grammar; each is refused.

    Without this the block is attributed to the ``flow:`` above it, carried
    over verbatim as foreign content, and the exporter-owned key inside it wins
    by PyYAML last-wins -- invisible to the ownership filter AND to the digest
    tripwire, because it travels inside foreign bytes.
    """
    path = _write(tmp_path / "demo.chiplet",
                  OWNED + FLOW + SMUGGLE_SPELLINGS[spelling])
    reason = cm.unwritable_reason(path)
    assert reason, "%s smuggled through the layout check" % spelling
    assert str(path) in reason and "Line " in reason
    assert "force=True does not bypass" in reason


def test_gui_tier_refusal_is_not_force_bypassable(tmp_path):
    """``force`` overrides the hand-edit tripwire, not an unreadable layout.

    It has to be outside the force arm: ``carry_over_foreign_blocks`` runs on
    the force path too, so a force-gated check would leave the whole defect
    live for any user who ever passes force.
    """
    path = _write(tmp_path / "demo.chiplet",
                  OWNED + FLOW + SMUGGLE_SPELLINGS["double_quoted"])
    # unwritable_reason takes no force argument BY CONSTRUCTION; the
    # orchestrator calls it before the `if not options.force:` arm.
    assert cm.unwritable_reason(path)


def test_gui_tier_accepts_the_documents_writers_actually_emit(tmp_path):
    """The shapes the ecosystem's writers produce must all pass.

    Column-0 ``- `` sequence items are the load-bearing one: ``yaml.dump`` does
    not indent a sequence under its key, so every document with a components
    list has them. A check that refused unmatched column-0 lines outright would
    reject every real .chiplet in the ecosystem.
    """
    canonical = ("# generated by the exporter\n" + OWNED + "\n"
                 + "# pinned by hand: do not reorder\n" + FLOW
                 + "netlist:\n  nets: []\n")
    assert cm.unwritable_reason(_write(tmp_path / "a.chiplet", canonical)) is None
    assert cm.unwritable_reason(
        _write(tmp_path / "b.chiplet", canonical.replace("\n", "\r\n"))) is None
    assert cm.unwritable_reason(
        _write(tmp_path / "c.chiplet", "---\n" + OWNED)) is None


# --------------------------------------------------------------------------
# PLUG-9: a line ends at LF, and at nothing else.
# --------------------------------------------------------------------------

#: Characters str.splitlines() breaks on, split by what PyYAML actually does
#: with them. Measured, because the first version of this file asserted they
#: were all "scalar content to YAML" and that sentence concealed a live smuggle.
#:
#: PyYAML REJECTS the whole document for these (ReaderError, non-printable), so
#: no reader accepts such a file and the grammar question never arises.
NON_PRINTABLE = {
    "vertical_tab": "\v",
    "form_feed": "\f",
    "file_separator": "\x1c",
    "group_separator": "\x1d",
    "record_separator": "\x1e",
}

#: PyYAML treats these as REAL line breaks. After a PLAIN scalar one of them
#: starts a new line for PyYAML and not for this grammar, which is the smuggle.
#: Telling that apart from the quoted case needs a YAML parser, which the GUI
#: tier does not have, so the write verdict refuses all four. Measured cost of
#: that bluntness: 0 refusals across 187 real .chiplet files.
#:
#: An earlier version of this comment said the quoted case is folded by PyYAML
#: and therefore safe. Both halves are wrong, and the correction is kept
#: because the mistake is instructive: it generalised from the KEY SETS
#: matching to the READERS matching. Measured inside a quoted scalar, CR and
#: NEL DO fold, to a single space, so the raw byte is gone and a reader that
#: preserves it returns a different string with no error raised anywhere;
#: U+2028 and U+2029 do not fold at all. So the quoted case is not the safe
#: one, it is the case where two readers disagree about a VALUE while agreeing
#: about the keys. The refusal is about RAW BYTES, and the escaped forms stay
#: legal, which is how these characters are meant to be written.
YAML_LINE_BREAKS = {
    "next_line": "\x85",
    "line_separator": "\u2028",
    "paragraph_separator": "\u2029",
    "carriage_return_alone": "\r",
}


@pytest.mark.parametrize("name", sorted(NON_PRINTABLE))
def test_a_non_printable_separator_is_a_document_no_reader_accepts(name):
    """Not our defect to fix: PyYAML refuses the file outright."""
    import yaml
    doc = ('format_version: "1.0"\nassembly:\n  name: "demo%sflow: injected"\n'
           % NON_PRINTABLE[name])
    with pytest.raises(yaml.YAMLError):
        yaml.safe_load(doc)


@pytest.mark.parametrize("name", sorted(YAML_LINE_BREAKS))
def test_a_yaml_line_break_refuses_the_rewrite(tmp_path, name):
    """The residual PLUG-9 left behind, and it inverts the original defect.

    Cutting only on LF is right for the grammar, but it means PyYAML can see a
    line break where the grammar sees none. A second ``components:`` written
    after a PLAIN scalar and separated by one of these lands inside a carried
    foreign block and wins by last-wins in the consumer. All four smuggled an
    owned block past both the layout refusal and the worker key-set check
    before this refusal existed.
    """
    brk = YAML_LINE_BREAKS[name]
    hostile = (OWNED + "flow:\n  steps: []%scomponents:\n"
               "- id: evil\n  layout: ${EVIL}/pwned.gds\n" % brk)
    path = _write(tmp_path / "demo.chiplet", hostile)
    reason = cm.unwritable_reason(path)
    assert reason, "the smuggle is open again"
    assert "line break" in reason


def test_a_crlf_document_is_not_mistaken_for_a_lone_carriage_return(tmp_path):
    """The first thing the break check got wrong: searching line by line ate
    the LF the ``\r(?!\n)`` lookahead needs, so every CRLF file was refused."""
    path = _write(tmp_path / "demo.chiplet",
                  (OWNED + FLOW).replace("\n", "\r\n"))
    assert cm.unwritable_reason(path) is None


def test_reading_a_document_does_not_translate_newlines(tmp_path):
    """``open(path)`` is universal-newlines and would undo the line grammar.

    A lone CR becomes LF in text mode, which puts back exactly the phantom key
    the LF-only cut removes -- and here it would make a valid document look
    like it names ``flow`` twice, i.e. the fix would refuse a good file.
    """
    doc = ('format_version: "1.0"\n'
           'assembly:\n  name: "demo\rflow: injected"\n' + FLOW)
    path = _write(tmp_path / "demo.chiplet", doc)
    assert cm.read_document(path) == doc
    assert cm.top_level_key_lines(cm.read_document(path)) == [
        "format_version", "assembly", "flow"]
    with open(path, "r", encoding="utf-8") as fh:          # the wrong way
        assert cm.top_level_key_lines(fh.read()).count("flow") == 2


def test_carry_over_keeps_crlf_line_endings_verbatim(tmp_path):
    """"Copied verbatim" has to mean the bytes, line endings included."""
    existing = _write(tmp_path / "demo.chiplet", (OWNED + FLOW).replace("\n", "\r\n"))
    staged = _write(tmp_path / "staged.chiplet", OWNED)
    assert cm.carry_over_foreign_blocks(existing, staged) == ["flow"]
    assert "flow:\r\n  steps: []" in cm.read_document(staged)


# --------------------------------------------------------------------------
# Worker tier: the same proposition, asked where both parsers exist.
# --------------------------------------------------------------------------

def _worker_gate():
    pytest.importorskip("yaml")
    pytest.importorskip("klayout")
    import hyp_to_gds
    return hyp_to_gds.chiplet_top_level_key_parity_error


def test_worker_gate_passes_a_canonical_document(tmp_path):
    gate = _worker_gate()
    assert gate(_write(tmp_path / "demo.chiplet", OWNED + FLOW)) is None


def test_worker_gate_catches_what_the_gui_tier_structurally_cannot(tmp_path):
    """A column-0 line inside a multi-line quoted scalar.

    Text alone cannot decide this: the line IS a well-formed key line, and
    knowing that it sits inside a scalar opened two lines earlier needs a
    parser. The GUI tier accepts the document (correctly -- it models every
    shape in it) and the parity check refuses it.
    """
    gate = _worker_gate()
    doc = ('format_version: "1.0"\n'
           'assembly:\n'
           '  name: "demo\n'
           'flow: injected"\n')
    path = _write(tmp_path / "demo.chiplet", doc)
    assert cm.unwritable_reason(path) is None              # GUI tier: passes
    reason = gate(path)
    assert reason and "flow" in reason                     # worker tier: refuses


def test_gui_tier_catches_what_the_worker_gate_structurally_cannot(tmp_path):
    """A quoted duplicate of an OWNED key, placed after a foreign block.

    The grammar attributes the quoted block to ``flow:``, carries it over as
    foreign, and PyYAML last-wins it over the exporter's regenerated
    components.

    The worker gate catches this one TOO, since switching it from
    ``safe_load`` to ``compose`` made the duplicate ``components`` visible
    where a dict had collapsed it. That is a strengthening, not a redundancy:
    the nets still cover different directions, and the case only the GUI tier
    can answer is a document whose bytes the grammar never attributed at all.
    Asserting the worker PASSED here, as this test first did, would pin the
    weaker behaviour and quietly forbid the fix.
    """
    gate = _worker_gate()
    doc = OWNED + FLOW + "'components':\n- id: interposer\n  layout: ${EVIL}/pwned.gds\n"
    path = _write(tmp_path / "demo.chiplet", doc)
    assert cm.unwritable_reason(path)                      # GUI tier: refuses
    assert gate(path)                                      # worker tier: also refuses


def test_a_repeated_top_level_key_is_refused_before_the_rewrite(tmp_path):
    """Both parsers see two ``flow`` keys, so parity AGREEING is correct here.

    The refusal is the GUI tier's, and it has to be: the splitter concatenates
    the two runs under the first occurrence, which is the one case where its
    own losslessness breaks (the bytes of any block between them move). The
    oracle carries this as a refuse row for exactly that reason.

    This test used to assert the worker gate caught it, on the premise that
    PyYAML collapses the repeat so only a multiset comparison sees it. Half
    true: ``compose`` does keep both, but so does the grammar, so they agree
    and there is nothing for parity to report. Agreement is the right answer
    from a check that only asks whether the two readers see the same thing.
    """
    gate = _worker_gate()
    path = _write(tmp_path / "demo.chiplet", OWNED + FLOW + "flow:\n  extra: true\n")
    reason = cm.unwritable_reason(path)
    assert reason and "twice" in reason
    assert gate(path) is None, "both readers see two keys; parity has nothing to add"


def test_worker_gate_refuses_a_key_yaml_does_not_read_as_text(tmp_path):
    """``on:`` is the key ``True`` to a YAML 1.1 loader and ``'on'`` here.

    The one honest false-positive class: the two parsers genuinely disagree
    about that key's identity, so the message names the key instead of
    pretending the document is malformed.
    """
    gate = _worker_gate()
    path = _write(tmp_path / "demo.chiplet", OWNED + "on:\n  a: 1\n")
    reason = gate(path)
    assert reason and "on" in reason and "bool" in reason
